# Generated by Django 3.1 on 2023-05-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresConnector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Todo',
        ),
    ]
