# Generated by Django 3.1 on 2023-05-11 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresConnector', '0002_auto_20230511_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 15, 38, 17, 137614)),
        ),
    ]
