# Generated by Django 3.1 on 2023-05-11 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresConnector', '0003_auto_20230511_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='id',
            new_name='todo_id',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 16, 20, 48, 364672)),
        ),
    ]
